### ISSUE TITLE
Store pointer to the generated mdp (& targets)

### ISSUE THREAD

**Issue by xblahoud** [FiMDP/FiMDPEnv#1]
After `UUVEnv.Env.create_consmdp` is called, the environment loses track of the generated consMDP. Accessing the corresponding CMDP directly from the EEVEnv.Env object would be more convenient than being forced to keep it in some other variable.

We can do `.get_consmdp` that would generate a new object when called for the first time, and return the one already generated otherwise.

**Comment by pthangeda** [comment]
One of the concerns with this proposed change is that if the user ever changes the reload states or target states of the environment object, the `.get_consmdp` would still return the stored CMDP object as it has no way of knowing the change in environment object parameters. A simpler change could be to simply modify `UUVEnv.Env.create_consmdp` to simultaneously generate and return the CMDP object based on current environment parameters (reload and targets) while also updating the CMDP object stored as a variable in instance of `UUVEnv.Env`. This way, the user can access the CMDP object without regenerating by using the variable and regenerating the CMDP object using `.create_consmdp` whenever he makes some changes to the environment object.

**Comment by xblahoud** [comment]
I can see that this was addressed by 5d4b010a896d53d170f3346a7ca22aae223c5e5a

> One of the concerns with this proposed change is that if the user ever changes the reload states or target states of the environment object, the .get_consmdp would still return the stored CMDP object as it has no way of knowing the change in environment object parameters.

This a good point. IO can now think about two use cases:
1.  **independent:** We generate a CMDP, change the reloads, and generate another CMDP with a different set of reload states. And we might want these 2 objects to be distinct.

2. **coupled:** We generate CMDP, change the reloads, and we might want to propagate this change to the mdp that is tight to the environment.

The option 2 can be achieved by using functions that modify the set of reload states, similarly to [CMDP class in FiMDP](https://github.com/xblahoud/FiMDP/blob/master/fimdp/consMDP.py#L146). To achieve 1 we need to generate an object that we do not store in the environment.

In fact, when we change the set of reload state, the structure of the CMDP remains the same and we do not need to regenerate that. We can just update the set of reload states of the CMDP object.

**Comment by pthangeda** [comment]
7d7dde195904b2710c404ebe8de3ba7973e7672f makes the changes for now to create the consMDP object using a separate method and a separate method to access the consMDP object and targets.
