### ISSUE TITLE
Support for multiple agents

### ISSUE THREAD

**Issue by pthangeda** [FiMDP/FiMDPEnv#3]
The current version of `UUVEnv` only supports tracking a single agent via the `Env` class. I propose creating a new class `MultiEnv` (better name suggestions are welcomed) that is designed to keep track of trajectories, action histories, energies and capacities of multiple agents operating on the same environment and hence have the same common CMDP object. Support for visualization tools for multiple agents is also desired. 

Alternatively, we could modify the existing `Env` class to accommodate 1 to n number of agents but I am afraid the changes required might break some of the existing integrations. Any suggestions on changing names of `Env` object and `MultiEnv` object to better reflect the fact that both represent a single environment but with single or multiple agents are also welcomed.

**Comment by xblahoud** [comment]
Regarding names, we can go with `SingleAgent` and `MultiAgent` as all are imported from `UUVEnv`.What might be a bit tricky is that there are many possibilities for how a multi-agent environment can work. 
* Do all agents move synchronously?
* Is the set of targets shared or each agent has a unique set of targets?
* Can they share reload states?
* They can even have different transitions/costs on the same set of states...

I suggest that we first define well the behavior and discuss what variants we consider to support in the future. This might help with naming.

**Comment by xblahoud** [comment]
`SynchornousMultiAgentEnv`could be:
* All agents must move in each step, they move synchronously.
* Each agent has its own target (this might be changed using a parameter).
* All reload states can be used by any agent.
* Transition structure is the same.
* Capacities can differ.

**Comment by pthangeda** [comment]
Synchronous multi-agent environment has been added in 6a8672ab65d69333199e4b0018b2055f0c3d7e64. I am closing this issue for now; feel free to open it if any new modifications are required.
