### ISSUE TITLE
Human-readable action names

### ISSUE THREAD

**Issue by xblahoud** [FiMDP/FiMDPEnv#4]
Currently, the labels of actions in the created CMDP are of the form `[source_sid, action]` where the `action` part is an integer, which is not very informative. As this is a string anyway, using integers does not save anything. We can use `N`, `S`, ... or `wN`, `wS`, ... for weak actions, and `sN`, `sS`, ... for strong actions. I am not sure if we need the `source_sid` (sid=state id) in there. We need to know this information to access the action anyway.

I plan to update the way strategies represent actions in [FiMDP](https://github.com/xblahoud/FiMDP). The new representation will store the whole `ActionData` object which also have the `source_sid`. See https://github.com/xblahoud/FiMDP/issues/25

**Comment by pthangeda** [comment]
This issue has been addressed in 6a8672ab65d69333199e4b0018b2055f0c3d7e64. I am closing this issue for now; feel free to open it if any new modifications are required.
